import { NextApiRequest, NextApiResponse } from 'next';

import { UserModel } from '@/models/UserModel';
import {
  createUserWithAutoId,
  createUserWithId,
  emailValidator,
} from '@/lib/userAPI';
import statusCodes from '@/httpStatusCodes';

export default async (req: NextApiRequest, res: NextApiResponse) => {
  emailValidator(req, res, async () => {
    if (req.method === 'POST') {
      const { email, id } = req.body;
      try {
        const findUser = await UserModel.findOne({ email });

        if (!findUser) {
          let newUser;

          if (id) {
            // Create a new user with a provided ID
            newUser = await createUserWithId(email, id);
          } else {
            // Create a new user with an autogenerated ID
            newUser = await createUserWithAutoId(email);
          }

          const newId = newUser._id;

          return res.status(statusCodes.OK).json({
            id: newId,
          });
        } else if (findUser && id) {
          // User already exists, and an ID was provided
          return res.status(statusCodes.CONFLICT).json(null);
        }

        // User exists, return their ID
        res.status(statusCodes.OK).json({
          id: findUser._id,
        });
      } catch (err) {
        // Handle errors
        res.status(statusCodes.INTERNAL_SERVER_ERROR).json({
          message: `An error occurred while logging in: ${err}`,
        });
      }
    }
  });
};
